import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import Link from 'next/link'
import { AuthPlanApp } from '@/components/AuthPlanApp.module'
import { Auth } from "@supabase/auth-ui-react"
import supabaseClient from '@/utils/supabaseClient'
import signIn from '../utils/signIn'

const inter = Inter({ subsets: ['latin'] })

export default function Home() { //pages配下なのでdefaultが必要
  
  return (
    <>
      <Head>
        <title>おでかけいかく</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>おでかけいかく</h1>
        <nav>
          <ul>
            <li>
              {/* Context を使用するには Provider コンポーネントで囲む必要があります */}
              <Auth.UserContextProvider supabaseClient={supabaseClient}>
                <AuthPlanApp supabaseClient={supabaseClient}>
                  <button onClick={() => signIn(supabaseClient)}>Googleでログイン</button>
                </AuthPlanApp>
              </Auth.UserContextProvider>
            </li>
            <li>
              {/* <Link href="/plan">
                ログイン
              </Link> */}
            </li>
          </ul>
        </nav>
      </header>
      <main>
        <section>
        </section>
      </main>
      <footer></footer>
    </>
  )
}
