import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head'
import { Header } from '@/components/Header'
import { Sidebar } from '@/components/Sidebar'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Plan.module.css'
import { Login } from '@/components/Login.module';
import { Logout } from '@/components/Logout.module';

const Plan: NextPage = () => {

  return (
    <>
      <Head>
        <title>おでかけいかく</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* ログインしている場合 */}
          <>
          <Header title="おでかけいかく" />
          <main className={styles.main}>
            <Sidebar title="sidebarタイトル" />
            <div className={styles.contents}>
                  <Image
                    src="/vercel.svg"
                    alt="Vercel Logo"
                    className={styles.vercelLogo}
                    width={100}
                    height={24}
                    priority
                  />
                  <div className={styles.card}>計画1</div>
                  <div className={styles.card}>計画2</div>
                  <div className={styles.card}>+</div>
            </div>
            <Logout />
          </main>
          </>
          
      {/* ログインしていない場合 */}
          <div>
            <p>ログインしていません</p>
            <Login />
            <Link href="/" >
              TOPへ戻る
            </Link>
          </div>
    </>
  );
};

export default Plan;