import React from 'react';
import { useSession, signIn, signOut } from 'next-auth/react';
import { NextPage } from 'next';
import Head from 'next/head'
import { Header } from '@/components/Header'
import { Sidebar } from '@/components/Sidebar'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Plan.module.css'

const Plan: NextPage = () => {
  // sessionの値のイメージ
  // {
  //  "user":{
  //    "name":"mk",
  //    "email":"XXXX@email.com",
  //    "image":"https://lh3.googleusercontent.com/a/ABCdef_GHijKlMn=s99-c"
  //  },
  //  "expires":"2023-04-25T12:30:59.000Z"
  // }
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>おでかけいかく</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        // セッションがある場合アプリを表示
        session && (
          <>
          <Header title="おでかけいかく" />
          <main className={styles.main}>
            <Sidebar title="sidebarのタイトルです" />
            <div className={styles.contents}>
                  <Image
                    src="/vercel.svg"
                    alt="Vercel Logo"
                    className={styles.vercelLogo}
                    width={100}
                    height={24}
                    priority
                  />
            </div>
          </main>
          </>
        )
      }
      {
        // セッションがない場合、ログインを表示
        // ログインボタンを押すと、ログインページに遷移する
        !session && (
          <div>
            <p>ログインしていません</p>
            <button onClick={() => signIn()}>ログイン</button>
            <Link href="/" >
              TOPへ戻る
            </Link>
          </div>
        )
      }
    </>
  );
};

export default Plan;